### PR TITLE
Fixes to types for new inquiry

### PR DESCRIPTION
**Pull request by dzucconi**
This PR corrects and adds a few things to support https://github.com/artsy/force/pull/8483

### CODE REVIEW

**Comment by abhitip** [comment]
Why is auth_redirect optional now? Is it because it would just be the inquiry modal for inquiry?

**Comment by dzucconi** [comment]
Yeah; it's not redirecting anywhere. You login and stay on the page and there's no redirect. Unless you want this param to be just whatever the current page is?

**Comment by abhitip** [comment]
I think that's what we've done in the past - like if you login on the artist page, it just stays on the artist page right? I think auth_redirect would be the artist page in that case. Could we just keep it at that?

**Comment by dzucconi** [comment]
@abhitip sure works for me. Updated.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v4.2.0`](https://github.com/artsy/cohesion/releases/tag/v4.2.0) :rocket:

**Pull request merged**
