### PR TITLE
Saved Search M2 tracking

### PR DESCRIPTION
**Pull request by louislecluse**
Tracking for Saved Search M2.

### CODE REVIEW

**Comment by dblandin** [comment]
@louislecluse Do these events describe the initial tap or when the action is performed?

For example, a user can click "Create alert" but abandon the flow. Similarly for deleting a saved search: a user can click "Remove alert" but then decide to keep it and dismiss the confirmation prompt.

**Comment by louislecluse** [comment]
For edit and delete, I was thinking of tracking when the action is performed.

For create alert I was thinking when user taps the "create alert" button, we already have the event that is fired when the alert is created ("toggled saved search").

**Comment by dblandin** [comment]
> For edit and delete, I was thinking of tracking when the action is performed.

In that case, should we rename the events to reflect that it's not just a tap but after the action is performed? Something like `editedSavedSearch` and `deletedSavedSearch`?

**Comment by louislecluse** [comment]
Good point, added relevant events.

**Review by dblandin — APPROVED** [review]

**Comment by artsyit** [comment]
:rocket: PR was released in [`v2.19.0`](https://github.com/artsy/cohesion/releases/tag/v2.19.0) :rocket:

**Pull request merged**
