### PR TITLE
New event and properties for Viewing Rooms on iOS

### PR DESCRIPTION
**Pull request by louislecluse**
Adds:
- tappedViewingRoomGroups
- 2 context modules for viewing room rails
- 2 owner types for viewing rooms

### CODE REVIEW

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.23.0`](https://github.com/artsy/cohesion/releases/tag/v1.23.0) :rocket:

**Comment by louislecluse** [comment]
@mikehrom mistakenly self merged 🤦
I don't think there is anything special but feel free to review and I will revert/add another PR if anything is missing!

**Comment by louislecluse** [comment]
@pvinis Some more work might be needed to consume the `tappedViewingRoomGroup` event in eigen!

**Comment by mikehrom** [comment]
@louislecluse 📣  party foul  📣 — I checked anyway and it looks good. Thanks for getting this in!

**Pull request merged**
