### PR TITLE
feat(CX-2457): added myCollectionArtworkAbout context module

### PR DESCRIPTION
**Pull request by dariakoko**
The type of this PR is: ** Enhancement**

This PR resolves [CX-2457]

### Description

Added myCollectionArtworkAbout context module
### PR Checklist (tick all before merging)

- [x] If I've added a new file to the tree I've exported it from the common `index.ts`
- [ ] I've added comments with examples for any new interfaces and ensured that they're in the docs
- [x] No platform-specific terminology has been used outside of `click` and `tap` (platform is inferred by the DB storing events)

[CX-2457]: https://artsyproduct.atlassian.net/browse/CX-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dariakoko** [comment]
I will merge this. Please, let me know some changes have to be made in this PR

**Comment by artsyit** [comment]
:rocket: PR was released in [`v4.42.0`](https://github.com/artsy/cohesion/releases/tag/v4.42.0) :rocket:

**Comment by MounirDhahri** [comment]
sounds good to me

**Comment by MounirDhahri** [comment]
@dariakoko I do believe you forgot to export here though https://github.com/artsy/cohesion/blob/8ca9d75f178f51d4fd3db1f59dd2efdc6f246bfb/src/Schema/Values/ContextModule.ts#L173

**Comment by dariakoko** [comment]
Hmmm, no, I didn't do this on purpose. I took the old module (sellFooter) as an example, it's not exported either. 
@audrey-thenot could you take a look, please?

**Pull request merged**
