### PR TITLE
@eessex => [OwnerType] Add collect page

### PR DESCRIPTION
**Pull request by mzikherman**
Adding collect page as an owner type.

### CODE REVIEW

**Comment by mzikherman** [comment]
I don't follow when one would use that vs `OwnerType`? For instance, I'm working on a Force PR that uses `OwnerType.artist` in tracking code, should that be `PageOwnerType` instead?

**Comment by eessex** [comment]
So the `OwnerType` is what you'd use in Force etc when implementing this. However, we use `PageOwnerType` on the schema side to enforce which `OwnerTypes` are exposed in web versus iOS environments.

**Comment by mzikherman** [comment]
Ah, gotcha! That makes a lot of sense.

**Comment by mzikherman** [comment]
Updated!

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.10.0`](https://github.com/artsy/cohesion/releases/tag/v1.10.0) :rocket:

**Pull request merged**
