### PR TITLE
Deprecate Helpers

### PR DESCRIPTION
**Pull request by pvinis**
The type of this PR is: **Enhancement**

### Description

As part of the accepted RFC https://github.com/artsy/cohesion/issues/212, I am making this PR to deprecate helpers. The next steps are to slowly remove them while we make changes to eigen and force to stop using them, bit by bit.

### PR Checklist (tick all before merging)

- [x] If I've added a new file to the tree I've exported it from the common `index.ts`
- [x] I've added comments with examples for any new interfaces or helpers and ensured that they're in the docs 
- [x] No platform-specific terminology has been used outside of `click` and `tap` (platform is inferred by the DB storing events)

### CODE REVIEW

**Review by mdole — APPROVED** [review]
👍 nice, this is a good first step towards deprecation! In case others haven't seen it, this message has a bit more details on the overall path to fully removing these from Cohesion: https://artsy.slack.com/archives/C015KTU8RQT/p1632308619004300

**Comment by pvinis** [comment]
I'll wait for at least one more review, then I will merge it.

**Review by damassi — APPROVED** [review]
Appreciatetd that these files were moved -- deprecated -- rather than deleted 👍 

LGTM! (Though we should probably add a `canary` tag to the PR as well and test things against that before merging.)

**Review by sweir27 — APPROVED** [review]
Agree with Chris about testing with a canary, but this is awesome! Thank you for continuing on with this work!!

**Comment by pvinis** [comment]
I did make a canary on https://github.com/artsy/cohesion/pull/235 and https://github.com/artsy/cohesion/pull/236 and they both worked fine on eigen and force 👍.

Thank you all for the reviews. I'll go ahead and merge, and go from there for the example PRs.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v4.0.0`](https://github.com/artsy/cohesion/releases/tag/v4.0.0) :rocket:

**Comment by dzucconi** [comment]
These should be marked with `@deprecated` so that our tooling picks it up?

**Comment by dzucconi** [comment]
Also what's the migration path for tracking authentication events or do we just migrate the helpers over? They need to be outside of components so we won't be using the hooks.

**Comment by dzucconi** [comment]
OK — I completely misunderstood what these functions did! I thought they were actually making calls to track!

**Comment by pvinis** [comment]
I didn't think of the @deprecated comment. that would be cool, but maybe too much work? 🤔

**Pull request merged**
